language: node_js
node_js:
  - "11.10.1"
cache:
  directories:
    - node_modules
script:
  - yarn install
  - yarn test
  - yarn run build
deploy:
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
